language: python
python:
  - "3.5"
before_install:
  - sudo apt-get update
  - sudo apt-get install -y libpcap-dev
install:
  - pip install -r requirements.txt
script:
  - nosetests test_wifiology_node_poc
