#!/usr/bin/env bash
set -eu

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
SCHEMA_FILE="$DIR/wifiology_node_poc/sql/schema.sql"
TARGET_DB="${1:-${DIR}/empty.db}"

if [ -e "${TARGET_DB}" ]; then
    rm "${TARGET_DB}"
fi

sqlite3 "${TARGET_DB}" < ${SCHEMA_FILE}
